version: "3.3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=claim
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  trust-claim-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trust-claim-backend
    depends_on:
      - postgres
    ports:
      - 9000:9000
    volumes:
      - ./build:/app/build
    restart: always

  trust-claim-data-pipeline:
    build:
      # get this from https://github.com/Whats-Cookin/trust-claim-data-pipeline
      context: ../trust-claim-data-pipeline
      dockerfile: Dockerfile
    container_name: trust-claim-data-pipeline
    environment:
      - DB_HOST=postgres
      - DB_NAME=claim
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
    restart: always
    depends_on:
      - postgres
    ports:
      - 5000:5000

volumes:
  postgres-data:
