name: Dispatch Update to Forks

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request in Fork
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Sync with upstream
          branch: sync-upstream
          delete-branch: true
          base: master
          body: "This PR merges the latest changes from the upstream repository into your fork."
          title: "Sync with upstream"
          upstream-repository: Whats-Cookin/trust_claim_backend_pipeline
