name: Call Webhook on Push or PR Merge to Master

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  call-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
        run: |
          curl -X POST http://68.183.144.184:8080/github-webhook/ \
          -H "Content-Type: application/json" \
          -d '{"event":"github", "action":"push or pull_request merged"}'

